### ISSUE TITLE
UObjects Created are not destroyed

### ISSUE THREAD

**Issue by koohz** [getsetgames/BlueprintReflection#1]
When creating an array of instantiated UObjects, these are stored like 

![](http://i.gyazo.com/d008b2f629c8ca3b1d98573543666e8f.png)

UObject_Child_C_0
UObject_Child_C_1
UObject_Child_C_2

![](http://i.gyazo.com/365e3d53271f91681c2ed8776ee502eb.png)

But when i re-run the game the previous objects are not destroyed and the next objects will be stored as

UObject_Child_C_3
UObject_Child_C_4
UObject_Child_C_5

![](http://i.gyazo.com/50ca09cebbeec7f577037b3067d69ddb.png)

So the prevously object will be not deleted/destructed from memory

(Thank you for this plugin)

**Comment by derekvanvliet** [comment]
Thanks, koMah. I have a few questions: 
1. In this example, is "Item" a blueprint class or a C++ class?
2. Where is your array stored? Is it a variable in a level?

**Comment by koohz** [comment]
It is a simple Inventory system. 
- A character that hold an Inventory Actor Blueprint Variable. 
- The Inventory Actor have an array of "Item" blueprints
- Item Blueprint is a direct child of UObject class

**Comment by koohz** [comment]
I've noticed now with cmartel's help that the counter after the class name, UObjectChildClass_**C_0**, is only a counter assigned from the editor. 

Refer to https://forums.unrealengine.com/showthread.php?59234-Custom-Inventory-System-Some-Questions&p=223562#post223562

**Comment by derekvanvliet** [comment]
Ah good. That means this isn't a bug, correct?

**Comment by koohz** [comment]
I'm currently check his test.

**Comment by derekvanvliet** [comment]
Okay, let me know if you still think this is a problem.
