### ISSUE TITLE
GetClassByName doesn't work on non-loaded classes

### ISSUE THREAD

**Issue by tinco** [getsetgames/BlueprintReflection#2]
Hi,

Thanks for the nice implementation, I noticed this only works if there's already an actor of the given class somewhere in the level. I asked a question on the forums and they told me to use LoadObject instead.

https://forums.unrealengine.com/showthread.php?57503-Spawn-actor-with-class-name-in-string

**Comment by derekvanvliet** [comment]
Thanks for the heads up about this, @d-snp
